---
# These tasks install http and the php modules.

- name: Install Zabbix RPM
  yum: name=http://repo.zabbix.com/zabbix/3.0/rhel/6/x86_64/zabbix-release-3.0-1.el6.noarch.rpm

- name: Install Zabbix Agent
  yum: name={{ item }} state=present
  with_items:
   - zabbix-agent

