---

- name: 全ノードに共通設定を適用する
  hosts: all
  remote_user: root

  roles:
    - common

# - name: configure and deploy the webservers and application code
#   hosts: webservers
#   remote_user: root
#   roles:
#     - web

- name: deploy PostgreSQL and configure the databases
  hosts: dbservers
  remote_user: root
  roles:
    - db

# - name: configure and deploy the zabbix-server
#   hosts: zabbix-server
#   remote_user: root
#   roles:
#     - zabbix
