---

- name: change listen_addresses to '*'
  lineinfile: dest=/var/lib/pgsql96/data/postgresql.conf
    regexp="^#listen_addresses"
    line="listen_addresses = '*'"
    state=present
    backup=yes
    
- name: Configure host based authentication (if entries are configured).
  template:
    src: "templates/pg_hba.conf.j2"
    dest: "{{ postgresql_config_path }}/pg_hba.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: 0600
  notify: restart postgresql96
  when: postgresql_hba_entries

- name: PostgreSQL start
  become: yes
  service:
    name=postgresql96
    state=restarted
    enabled=yes
