---

- name: add user to PostgreSQL
  become: yes
  become_user: postgres
  become_method: su
  postgresql_user:
    name: "{{ app_user }}"
    password: "{{ app_password }}"
    role_attr_flags: CREATEDB,NOSUPERUSER
  
- name: Create Database PostgreSQL
  become: yes
  become_user: postgres
  become_method: su
  postgresql_db:
    name=redmine
    encoding='UTF-8'
    lc_collate='ja_JP.UTF-8'
    lc_ctype='ja_JP.UTF-8'
    template='template0'
  notify: restart postgresql96
