---
# PostgreSQL 初期設定用の playbook 

- name: Install RHEL 6 yum repo for PostgreSQL
  yum: name=https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-6-x86_64/pgdg-ami201503-96-9.6-2.noarch.rpm state=installed

- name: Install PostgreSQL package
  yum: name={{ item }} state=installed
  with_items:
   - "{{ postgresql_python_library }}"
   - postgresql96
   - postgresql96-server
   - postgresql96-devel 
   - postgresql96-contrib
   - python27-psycopg2
  tags:
    - packages

- include: initialize.yml
- include: configure.yml
- include: database.yml

# database user operation
# yum install -y  https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-redhat10-10-2.noarch.rpm
# sed -i "s/rhel-\$releasever-\$basearch/rhel-latest-x86_64/g" "/etc/yum.repos.d/pgdg-10-redhat.repo"
# shell: sed -i "s/rhel-\$releasever-\$basearch/rhel-latest-x86_64/g" ""
# yum info postgresql10

# https://qiita.com/KAZAMAI_NaruTo/items/600c5f108ca768025da2
# localedef -i ja_JP -c -f UTF-8 -A /usr/share/locale/locale.alias ja_JP.UTF-8