---
# Handler to handle DB tier notifications

- name: start postgresql96
  service: name=postgresql96 state=started enabled=yes

- name: restart postgresql96 
  service: name=postgresql96 state=restarted
