---

# Install and setting php
- name: Install php
  yum: name={{ item }} state=latest
  with_items:
    - php71
    - php71-gd
    - php71-mysqlnd
    - php71-bcmath
    - php71-mbstring
    - php71-xml
    - php71-ldap

- name: set php timezone
  lineinfile: >- 
    dest='/etc/php.ini'
    regexp="^date.timezone ="
    insertafter="^;date.timezone ="
    line="date.timezone = {{ dateTimezone }}"
