---
- include: install_mariadb.yml
- include: install_httpd.yml
- include: install_php.yml
- include: install_epel.yml
- include: install_zabbix.yml


- name: 日本語ロケールの追加
  shell: localedef -f UTF-8 -i ja_JP ja_JP

# Setting database
- name: Create a new database
  mysql_db: name={{ DBName }} state=present encoding=utf8 collation=utf8_bin

- name: Create database user and 'WITH GRANT OPTION'
  mysql_user: name={{ DBUser }} password={{ DBPassword }} priv={{ DBName }}.*:ALL,GRANT state=present

- name: Importing schema file
  shell: mysql -u{{ DBUser }} -p{{ DBPassword }} {{ DBName }} -e "show tables;" | wc -l
  register: zabbixDatabaseTebles
  changed_when: False

- name: Importing SQL
  shell: zcat /usr/share/doc/zabbix-server-mysql-*/create.sql.gz | mysql -u{{ DBUser }} -p{{ DBPassword }} {{ DBName }}
  when: zabbixDatabaseTebles|int == 0

# Setting zabbix_server.conf
- name: Setting zabbix_server.conf
  lineinfile: >-
    dest='/etc/zabbix/zabbix_server.conf'
    regexp='{{ item.regexp }}'
    insertafter='{{ item.insertafter }}'
    line='{{ item.line }}'
  with_items:
    - regexp: '^ListenPort='
      insertafter: "^# ListenPort="
      line: 'ListenPort={{ ListenPort }}'
    - regexp: '^LogFile='
      insertafter: "^# LogFile="
      line: 'LogFile={{ LogFile }}'
    - regexp: '^DBHost='
      insertafter: "^# DBHost="
      line: 'DBHost={{ DBHost }}'
    - regexp: '^DBName='
      insertafter: "^# DBName="
      line: 'DBName={{ DBName }}'
    - regexp: '^DBUser='
      insertafter: "^# DBUser="
      line: 'DBUser={{ DBUser }}'
    - regexp: '^DBPassword='
      insertafter: "^# DBPassword="
      line: 'DBPassword={{ DBPassword }}'
    - regexp: '^DBPort='
      insertafter: "^# DBPort="
      line: 'DBPort={{ DBPort }}'
    - regexp: '^DBSocket='
      insertafter: "^# DBSocket="
      line: 'DBSocket={{ DBSocket }}'

# Copy a new 'zabbix.conf.php' file into place
- template: src=zabbix.conf.php.j2 dest=/etc/zabbix/web/zabbix.conf.php owner=apache group=apache mode=0644

- name: start zabbix-server 
  service: name=zabbix-server state=started enabled=yes

- name: restart httpd
  service: name=httpd state=restarted
