---
- hosts: all
  vars:
  remote_user: root
  sudo: no

# checked -> CentOS7.1

  handlers:
  - name: httpd restart
    service: name=httpd state=restarted

  tasks:
  - name: enable ius reposiotry
    yum: name={{ item }} state=installed
    with_items:
     - https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-14.ius.centos7.noarch.rpm
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

  - name: install php packages
    yum: name={{ item }} state=installed
    with_items:
     - php56u
     - php56u-opcache
     - php56u-pdo
     - php56u-pgsql
     - php56u-mbstring
     - php56u-mcrypt
    notify: httpd restart
