---
- hosts: all
  vars:
  remote_user: root
  sudo: no

# checked -> CentOS7.1

  handlers:

  tasks:
  - name: enable ius reposiotry
    yum: name={{ item }} state=installed
    with_items:
     - http://yum.postgresql.org/9.4/redhat/rhel-7-x86_64/pgdg-centos94-9.4-1.noarch.rpm
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

  - name: install postgresql-client packages
    yum: name={{ item }} state=installed
    with_items:
     - postgresql94
